# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('index', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.Garment')),
            ],
        ),
    ]
