# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0003_auto_20181031_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='garments.GarmentSize'),
        ),
    ]
