# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('garments', '0004_garment_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGarment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons.DropDate')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.GarmentFabric')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.GarmentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='garment',
            name='descrption',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='drop_date',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='sizes',
        ),
        migrations.AddField(
            model_name='garment',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.GarmentSize'),
        ),
        migrations.AddField(
            model_name='garment',
            name='base_garment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.BaseGarment'),
        ),
    ]
