# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0005_auto_20181031_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='sizes',
            new_name='size',
        ),
    ]
