# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='descrption',
            new_name='description',
        ),
    ]
